name: .NET Core

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]
    
env:
  SOLUTION_PATH: "src/Trakx.Dotnet.Utils.sln"
  PROJECT_PATH: "src/Trakx.Dotnet.Utils/Trakx.Dotnet.Utils.csproj"
  
jobs: 
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore ${{env.SOLUTION_PATH}}
    - name: Build
      run: dotnet build ${{env.SOLUTION_PATH}} --configuration Release --no-restore
