name: Publish nuget packages

on:
  workflow_dispatch:
    inputs:
      semverIncrementLevel:
        description: 'Level of the semver (major.minor.patch) to be increased to get the new package version.'
        required: true
        default: 'patch'
      debuggable:
        description: 'Set to false if you want a non debuggable (Release) package.'
        required: true
        default: 'true'
  push:
    branches:
      - master

env:
  SOLUTION_PATH: "src/Trakx.Utils.sln"
  UTILS_PROJECT_PATH: "src/Trakx.Utils/Trakx.Utils.csproj"
  TESTING_PROJECT_PATH: "src/Trakx.Utils.Testing/Trakx.Utils.Testing.csproj"
  STARTUP_PROJECT_PATH: "src/Trakx.Utils.Startup/Trakx.Utils.Startup.csproj"
  CACHING_PROJECT_PATH: "src/Trakx.Utils.Caching/Trakx.Utils.Caching.csproj"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Set compilation mode
        id: comp-mode
        run: |
          DEBUGGABLE="${{github.event.inputs.debuggable}}"
          DEBUGGABLE=${DEBUGGABLE:-true}
          if [ [DEBUGGABLE == f*] -o [DEBUGGABLE == F*] ]; then
            COMP_MODE=Release
          else
            COMP_MODE=Debug
          fi
          echo '::set-output name=compilationMode::'$COMP_MODE
          echo "compilation mode set to $COMP_MODE"

      - name: checkout
        uses: actions/checkout@v3

      - name: Bump version
        id: bumpVersion
        uses: trakx/bump-version-action@v8
        with:
          semverIncrementLevel: ${{github.event.inputs.semverIncrementLevel}}
          releaseBranches: master
          githubToken: ${{secrets.GITHUB_TOKEN}}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Add github nuget source
        run: dotnet nuget add source "https://nuget.pkg.github.com/trakx/index.json" --name "github" --username "trakx-bot" --password ${{secrets.TRAKX_BOT_READONLY_PAT}} --store-password-in-clear-text

      - name: Install dependencies
        run: dotnet restore ${{env.SOLUTION_PATH}}

      - name: Remove github source
        run: dotnet nuget remove source "github"

      - name: Build
        run: dotnet build ${{env.SOLUTION_PATH}} --configuration ${{steps.comp-mode.outputs.compilationMode}} --no-restore

      - name: Test
        run: dotnet test ${{env.SOLUTION_PATH}} --no-restore --verbosity normal

      - name: Package
        run: |
          dotnet pack ${{env.UTILS_PROJECT_PATH}} --no-build --configuration ${{ steps.comp-mode.outputs.compilationMode }} \
            --output ./nuget/ -p:PackageVersion=${{ steps.bumpVersion.outputs.fullVersion }} --include-symbols --include-source
          dotnet pack ${{env.TESTING_PROJECT_PATH}} --no-build --configuration ${{ steps.comp-mode.outputs.compilationMode }} \
            --output ./nuget/ -p:PackageVersion=${{ steps.bumpVersion.outputs.fullVersion }} --include-symbols --include-source
          dotnet pack ${{env.STARTUP_PROJECT_PATH}} --no-build --configuration ${{ steps.comp-mode.outputs.compilationMode }} \
            --output ./nuget/ -p:PackageVersion=${{ steps.bumpVersion.outputs.fullVersion }} --include-symbols --include-source
          dotnet pack ${{env.CACHING_PROJECT_PATH}} --no-build --configuration ${{ steps.comp-mode.outputs.compilationMode }} \
            --output ./nuget/ -p:PackageVersion=${{ steps.bumpVersion.outputs.fullVersion }} --include-symbols --include-source

      - name: Publish
        # https://github.com/NuGet/Home/issues/8580
        run: |
          ls ./nuget/*.nupkg
          for f in ./nuget/*.symbols.nupkg; do echo "pushing $f file.." && dotnet nuget push $f --api-key ${{secrets.GITHUB_TOKEN}} \
            --source "https://nuget.pkg.github.com/trakx/index.json"; done

      - name: push version tag
        uses: anothrNick/github-tag-action@1.38.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CUSTOM_TAG: v${{steps.bumpVersion.outputs.fullVersion}}
